version: 0.2

phases:
  install:
    commands:
      - echo "Installing Docker..."
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      - echo "Docker installation completed"
  pre_build:
    commands:
      - echo "Starting the pre-build phase..."
      - echo "Checking out the source code..."
      - echo "bhaiyya code clone ho gaya"  # The code is already cloned by CodePipeline
  build:
    commands:
      - echo "Starting the build phase..."
      - echo "Building the Docker image..."
      - docker build -t node-app-test-new .
      - echo "code build bhi ho gaya"
  post_build:
    commands:
      - echo "Starting the post-build phase..."
      - echo "Scanning the Docker image..."
      - echo "image scanning ho gayi"
      - echo "Pushing the Docker image to Docker Hub..."
      - echo "Logging in to Docker Hub..."
      - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
      - echo "Tagging the Docker image..."
      - docker tag node-app-test-new:latest ${DOCKERHUB_USERNAME}/node-app-test-new:latest
      - echo "Pushing the Docker image..."
      - docker push ${DOCKERHUB_USERNAME}/node-app-test-new:latest
      - echo "image push ho gaya"
      - echo "Deploying the Docker image..."
      - docker-compose down && docker-compose up -d
      - echo "deployment ho gayi"

env:
  variables:
    DOCKERHUB_USERNAME: "maulikmqs"
    DOCKERHUB_PASSWORD: "P4Vp?ZqK9cr+Aiz"

artifacts:
  files:
    - '**/*'
