version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Docker..."
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      - echo "Installing Docker Compose..."
      - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - sudo chmod +x /usr/local/bin/docker-compose
      - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
      - docker-compose version
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
  build:
    commands:
      - echo "Building Docker images..."
      - docker-compose build
  post_build:
    commands:
      - echo "Starting Docker containers..."
      - docker-compose down
      - docker-compose up -d
      - echo "Deployment completed."

env:
  variables:
    DOCKERHUB_USERNAME: maulikmqs
    DOCKERHUB_PASSWORD: P4Vp?ZqK9cr+Aiz

artifacts:
  files:
    - '**/*'
